import Foundation

enum ID3FrameNames {
    private static let names: [String: String] = [
        "AENC": "Audio encryption",
        "APIC": "Attached picture",
        "ASPI": "Audio seek point index",
        "CHAP": "Chapter",
        "COMM": "Comment",
        "COMR": "Commercial frame",
        "CTOC": "Table of contents",
        "ENCR": "Encryption method registration",
        "EQU2": "Equalisation",
        "ETCO": "Event timing codes",
        "GEOB": "General encapsulated object",
        "GRID": "Group identification registration",
        "LINK": "Linked information",
        "MCDI": "Music CD identifier",
        "MLLT": "MPEG location lookup table",
        "OWNE": "Ownership frame",
        "PCNT": "Play counter",
        "POPM": "Popularimeter",
        "POSS": "Position synchronisation",
        "PRIV": "Private frame",
        "RBUF": "Recommended buffer size",
        "RVA2": "Relative volume adjustment",
        "RVRB": "Reverb",
        "SEEK": "Seek frame",
        "SIGN": "Signature frame",
        "SYLT": "Synchronized lyrics",
        "SYTC": "Synchronized tempo codes",
        "TALB": "Album",
        "TBPM": "Beats per minute",
        "TCOM": "Composer",
        "TCON": "Content type",
        "TCOP": "Copyright",
        "TDEN": "Encoding time",
        "TDLY": "Playlist delay",
        "TDOR": "Original release time",
        "TDRC": "Recording time",
        "TDRL": "Release time",
        "TDTG": "Tagging time",
        "TENC": "Encoded by",
        "TEXT": "Lyricist",
        "TFLT": "File type",
        "TIPL": "Involved people",
        "TIT1": "Content group",
        "TIT2": "Title",
        "TIT3": "Subtitle",
        "TKEY": "Initial key",
        "TLAN": "Language",
        "TLEN": "Length",
        "TMCL": "Musician credits",
        "TMED": "Media type",
        "TMOO": "Mood",
        "TOAL": "Original album",
        "TOFN": "Original filename",
        "TOLY": "Original lyricist",
        "TOPE": "Original artist",
        "TOWN": "File owner",
        "TPE1": "Lead artist",
        "TPE2": "Album artist",
        "TPE3": "Conductor",
        "TPE4": "Interpreted by",
        "TPOS": "Disc number",
        "TPRO": "Produced notice",
        "TPUB": "Publisher",
        "TRCK": "Track number",
        "TRSN": "Internet radio station",
        "TRSO": "Internet radio owner",
        "TSOA": "Album sort order",
        "TSOP": "Performer sort order",
        "TSOT": "Title sort order",
        "TSRC": "ISRC",
        "TSSE": "Encoding settings",
        "TSST": "Set subtitle",
        "TXXX": "User text",
        "UFID": "Unique file identifier",
        "USER": "Terms of use",
        "USLT": "Unsynchronized lyrics",
        "WCOM": "Commercial URL",
        "WCOP": "Copyright URL",
        "WOAF": "Official audio file URL",
        "WOAR": "Official artist URL",
        "WOAS": "Official audio source URL",
        "WORS": "Official radio station URL",
        "WPAY": "Payment URL",
        "WPUB": "Publisher URL",
        "WXXX": "User URL"
    ]

    static func name(for frameID: String) -> String {
        names[frameID] ?? frameID
    }
}
